// User findAll
GET http://localhost:5000/user HTTP/1.1

###

// User findOne
GET http://localhost:5000/user/1 HTTP/1.1

###

// User create
POST http://localhost:5000/user/register HTTP/1.1
content-type: application/json

{
  "email": "badjojo@hotmail.fr",
  "password": "12345678"
}

###

// User update
PUT http://localhost:5000/user/2 HTTP/1.1
content-type: application/json

{
  "email": "jojo@hotmail.fr",
  "password": "12345678"
}

###

// User logout
GET http://localhost:5000/logout HTTP/1.1

###