CREATE TABLE api_user (
	id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email text NOT NULL UNIQUE,
	password text NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NULL
);

CREATE TABLE api_event (
	id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"time" text NOT NULL,
	training_type text NOT NULL,
	weight int NULL,
	user_id int NOT NULL REFERENCES api_user(id),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NULL
)